name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install valgrind
        run: sudo apt-get update && sudo apt-get install -y valgrind
      - name: Build
        run: make CFLAGS="-g -Wall -Wextra -std=gnu11 -Werror"
      - name: Test
        run: make test
